name: Build Android Xposed Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode signing key
      run: |
        mkdir -p app
        echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > app/release.keystore
      env:
        RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build APK with Gradle
      run: gradle assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: DisableVerify-apk
        path: app/build/outputs/apk/release/*.apk
